import type { ComponentStylesheets } from "../../natural-html/design-system.ts";

export const contextHeaderStyles: ComponentStylesheets = [
  {
    "context-header-left": {
      display: "flex",
      alignItems: "center",
      gap: "24px",
    },
    "context-brand": {
      display: "flex",
      alignItems: "center",
      gap: "10px",
      textDecoration: "none",
      color: "#ffffff",
      fontWeight: 600,
      fontSize: "15px",
    },
    "context-brand-icon": {
      width: "28px",
      height: "28px",
      background: "linear-gradient(135deg, #f97316 0%, #ea580c 100%)",
      borderRadius: "6px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      color: "white",
      fontSize: "12px",
      fontWeight: "bold",
    },
    "context-nav": {
      display: "flex",
      alignItems: "center",
      gap: "4px",
    },
    "context-nav-link": {
      display: "flex",
      alignItems: "center",
      gap: "6px",
      padding: "6px 12px",
      borderRadius: "6px",
      textDecoration: "none",
      color: "#a3a3a3",
      fontSize: "13px",
      fontWeight: 500,
      transition: "all 0.15s ease",
    },
    "context-nav-link-active": {
      color: "#ffffff",
      background: "#262626",
    },
    "context-header-right": {
      display: "flex",
      alignItems: "center",
      gap: "8px",
    },
    "context-icon-btn": {
      width: "36px",
      height: "36px",
      border: "none",
      background: "transparent",
      borderRadius: "6px",
      color: "#a3a3a3",
      cursor: "pointer",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      position: "relative",
      transition: "all 0.15s ease",
    },
    "notification-badge": {
      position: "absolute",
      top: "6px",
      right: "6px",
      width: "8px",
      height: "8px",
      background: "#f97316",
      borderRadius: "50%",
      border: "2px solid #0a0a0a",
    },
    "context-divider": {
      width: "1px",
      height: "24px",
      background: "#333333",
      margin: "0 8px",
    },
    "context-user": {
      display: "flex",
      alignItems: "center",
      gap: "8px",
      padding: "4px 8px 4px 4px",
      borderRadius: "6px",
      cursor: "pointer",
      transition: "all 0.15s ease",
    },
    "context-avatar": {
      width: "28px",
      height: "28px",
      borderRadius: "50%",
      background: "linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%)",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      color: "white",
      fontSize: "11px",
      fontWeight: 600,
    },
    "context-user-name": {
      fontSize: "13px",
      color: "#e5e5e5",
      fontWeight: 500,
    },
    "context-user-chevron": {
      color: "#737373",
    },
  },
];
