import type { ComponentStylesheets } from "../../natural-html/design-system.ts";

export const contentStyles: ComponentStylesheets = [
  {
    "content-wrapper": {
      maxWidth: "100%",
    },
    "page-header": {
      marginBottom: "40px",
      paddingTop: "16px",
    },
    "page-title": {
      fontSize: "32px",
      fontWeight: 700,
      color: "#0a0a0a",
      marginBottom: "12px",
      letterSpacing: "-0.5px",
    },
    "page-description": {
      fontSize: "16px",
      color: "#525252",
      lineHeight: 1.7,
      marginBottom: "20px",
    },
    "page-actions": {
      display: "flex",
      gap: "8px",
    },
    "action-btn": {
      display: "flex",
      alignItems: "center",
      gap: "6px",
      padding: "8px 14px",
      background: "#ffffff",
      border: "1px solid #e5e5e5",
      borderRadius: "6px",
      fontSize: "13px",
      fontWeight: 500,
      color: "#525252",
      cursor: "pointer",
      transition: "all 0.15s ease",
    },
    "action-btn-primary": {
      background: "#0a0a0a",
      borderColor: "#0a0a0a",
      color: "#ffffff",
    },
    "section-heading": {
      fontSize: "22px",
      fontWeight: 600,
      color: "#0a0a0a",
      marginTop: "48px",
      marginBottom: "16px",
      paddingBottom: "8px",
      borderBottom: "1px solid #e5e5e5",
      display: "flex",
      alignItems: "center",
      gap: "8px",
    },
    "anchor-link": {
      color: "#737373",
      textDecoration: "none",
      opacity: 0,
      transition: "opacity 0.15s ease",
    },
    "subsection-heading": {
      fontSize: "18px",
      fontWeight: 600,
      color: "#0a0a0a",
      marginTop: "32px",
      marginBottom: "12px",
    },
    "body-text": {
      fontSize: "15px",
      color: "#404040",
      lineHeight: 1.8,
      marginBottom: "20px",
    },
    "type-scale-title": {
      fontSize: "32px",
      fontWeight: 700,
      marginBottom: "8px",
      display: "block",
    },
    "type-scale-section": {
      fontSize: "22px",
      fontWeight: 600,
      marginBottom: "8px",
      display: "block",
    },
    "type-scale-subsection": {
      fontSize: "18px",
      fontWeight: 600,
      marginBottom: "8px",
      display: "block",
    },
    "type-scale-body": {
      fontSize: "15px",
      marginBottom: "8px",
      display: "block",
    },
    "type-scale-small": {
      fontSize: "13px",
      color: "#737373",
      display: "block",
    },
    "feature-grid": {
      display: "grid",
      gridTemplateColumns: "repeat(2, 1fr)",
      gap: "16px",
      margin: "24px 0",
    },
    "feature-card": {
      background: "#ffffff",
      border: "1px solid #e5e5e5",
      borderRadius: "12px",
      padding: "20px",
      cursor: "pointer",
      transition: "all 0.2s ease",
    },
    "feature-icon": {
      width: "40px",
      height: "40px",
      background: "#f5f5f5",
      borderRadius: "8px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      marginBottom: "12px",
      fontSize: "18px",
    },
    "feature-title": {
      fontSize: "15px",
      fontWeight: 600,
      color: "#0a0a0a",
      marginBottom: "6px",
    },
    "feature-desc": {
      fontSize: "13px",
      color: "#737373",
      lineHeight: 1.6,
    },
    callout: {
      background: "#fffbeb",
      border: "1px solid #fde68a",
      borderLeft: "4px solid #f59e0b",
      borderRadius: "8px",
      padding: "16px 20px",
      margin: "24px 0",
    },
    "callout-header": {
      display: "flex",
      alignItems: "center",
      gap: "8px",
      fontWeight: 600,
      fontSize: "14px",
      color: "#0a0a0a",
      marginBottom: "8px",
    },
    "callout-content": {
      fontSize: "14px",
      color: "#404040",
      lineHeight: 1.7,
    },
    "definition-list": {
      margin: "24px 0",
    },
    "definition-item": {
      padding: "16px 0",
      borderBottom: "1px solid #e5e5e5",
    },
    "definition-term": {
      fontWeight: 600,
      fontSize: "15px",
      color: "#0a0a0a",
      marginBottom: "4px",
    },
    "definition-desc": {
      fontSize: "14px",
      color: "#525252",
      lineHeight: 1.7,
    },
    "code-block": {
      background: "#1e1e1e",
      borderRadius: "8px",
      padding: "16px 20px",
      margin: "16px 0",
      overflowX: "auto",
    },
    "code-block-enhanced": {
      background: "#1e1e1e",
      borderRadius: "10px",
      margin: "20px 0",
      overflow: "hidden",
      border: "1px solid #333",
    },
    "code-header": {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      padding: "10px 16px",
      background: "#2d2d2d",
      borderBottom: "1px solid #404040",
    },
    "code-header-left": {
      display: "flex",
      alignItems: "center",
      gap: "10px",
    },
    "code-filename": {
      fontSize: "13px",
      fontWeight: 500,
      color: "#e0e0e0",
      fontFamily: "SF Mono, Monaco, monospace",
    },
    "code-lang-badge": {
      fontSize: "10px",
      fontWeight: 600,
      textTransform: "uppercase",
      padding: "2px 8px",
      borderRadius: "4px",
      background: "#404040",
      color: "#a0a0a0",
    },
    "code-copy-btn": {
      display: "flex",
      alignItems: "center",
      gap: "6px",
      padding: "6px 10px",
      background: "transparent",
      border: "1px solid #404040",
      borderRadius: "6px",
      color: "#a0a0a0",
      fontSize: "12px",
      cursor: "pointer",
      transition: "all 0.15s ease",
    },
    "code-content": {
      padding: "16px 20px",
      overflowX: "auto",
    },
    "code-line": {
      display: "flex",
    },
    "line-number": {
      color: "#505050",
      textAlign: "right",
      paddingRight: "16px",
      minWidth: "32px",
      userSelect: "none",
    },
    "line-content": {
      flex: "1",
    },
    "tabs-container": {
      margin: "24px 0",
      border: "1px solid #e5e5e5",
      borderRadius: "10px",
      overflow: "hidden",
      background: "#fff",
    },
    "tabs-header": {
      display: "flex",
      background: "#f5f5f5",
      borderBottom: "1px solid #e5e5e5",
    },
    "tab-button": {
      padding: "12px 20px",
      fontSize: "13px",
      fontWeight: 500,
      color: "#525252",
      background: "transparent",
      border: "none",
      cursor: "pointer",
      position: "relative",
      transition: "all 0.15s ease",
    },
    "tab-content": {
      padding: "0",
      display: "none",
    },
    "steps-container": {
      margin: "24px 0",
      position: "relative",
    },
    step: {
      display: "flex",
      gap: "20px",
      paddingBottom: "32px",
      position: "relative",
    },
    "step-indicator": {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      flexShrink: 0,
    },
    "step-number": {
      width: "32px",
      height: "32px",
      background: "#f97316",
      color: "white",
      borderRadius: "50%",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: "14px",
      fontWeight: 600,
      position: "relative",
      zIndex: 1,
    },
    "step-line": {
      width: "2px",
      flex: 1,
      background: "#e5e5e5",
      marginTop: "8px",
    },
    "step-content": {
      flex: 1,
      paddingTop: "4px",
    },
    "step-title": {
      fontSize: "16px",
      fontWeight: 600,
      color: "#0a0a0a",
      marginBottom: "8px",
    },
    "step-description": {
      fontSize: "14px",
      color: "#525252",
      lineHeight: 1.7,
    },
    "file-tree": {
      background: "#fafafa",
      border: "1px solid #e5e5e5",
      borderRadius: "10px",
      padding: "16px 20px",
      margin: "20px 0",
      fontFamily: "SF Mono, Monaco, monospace",
      fontSize: "13px",
    },
    "file-tree-item": {
      display: "flex",
      alignItems: "center",
      gap: "8px",
      padding: "4px 0",
      color: "#404040",
    },
    "file-tree-children": {
      paddingLeft: "24px",
      borderLeft: "1px dashed #d4d4d4",
      marginLeft: "7px",
    },
    accordion: {
      margin: "20px 0",
      border: "1px solid #e5e5e5",
      borderRadius: "10px",
      overflow: "hidden",
    },
    "accordion-item": {
      borderBottom: "1px solid #e5e5e5",
    },
    "accordion-header": {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      padding: "16px 20px",
      background: "#fff",
      cursor: "pointer",
    },
    "accordion-icon": {
      width: "20px",
      height: "20px",
      color: "#737373",
      transition: "transform 0.2s ease",
    },
    "accordion-title": {
      fontSize: "15px",
      fontWeight: 500,
      color: "#0a0a0a",
    },
    "accordion-content": {
      padding: "0 20px 16px",
      fontSize: "14px",
      color: "#525252",
      lineHeight: 1.7,
      display: "none",
    },
    "api-table": {
      width: "100%",
      margin: "20px 0",
      border: "1px solid #e5e5e5",
      borderRadius: "10px",
      overflow: "hidden",
      borderCollapse: "separate",
      borderSpacing: "0",
    },
    "api-table-header": {
      textAlign: "left",
      padding: "12px 16px",
      background: "#f5f5f5",
      fontSize: "12px",
      fontWeight: 600,
      color: "#525252",
      textTransform: "uppercase",
      letterSpacing: "0.5px",
      borderBottom: "1px solid #e5e5e5",
    },
    "api-table-cell": {
      padding: "12px 16px",
      fontSize: "14px",
      color: "#404040",
      borderBottom: "1px solid #e5e5e5",
      verticalAlign: "top",
    },
    "prop-name": {
      fontFamily: "SF Mono, Monaco, monospace",
      fontSize: "13px",
      color: "#e11d48",
      background: "#fef2f2",
      padding: "2px 6px",
      borderRadius: "4px",
    },
    "prop-type": {
      fontFamily: "SF Mono, Monaco, monospace",
      fontSize: "12px",
      color: "#3b82f6",
    },
    "prop-default": {
      fontFamily: "SF Mono, Monaco, monospace",
      fontSize: "12px",
      color: "#737373",
    },
    "prop-required": {
      fontFamily: "SF Mono, Monaco, monospace",
      fontSize: "11px",
      color: "#dc2626",
      background: "#fef2f2",
      padding: "2px 6px",
      borderRadius: "4px",
      marginLeft: "6px",
    },
    badge: {
      display: "inline-flex",
      alignItems: "center",
      gap: "4px",
      padding: "3px 8px",
      fontSize: "11px",
      fontWeight: 600,
      borderRadius: "6px",
      textTransform: "uppercase",
      letterSpacing: "0.3px",
    },
    "badge-default": {
      background: "#f5f5f5",
      color: "#525252",
    },
    "badge-primary": {
      background: "#fff7ed",
      color: "#ea580c",
    },
    "badge-success": {
      background: "#f0fdf4",
      color: "#16a34a",
    },
    "badge-warning": {
      background: "#fffbeb",
      color: "#d97706",
    },
    "badge-error": {
      background: "#fef2f2",
      color: "#dc2626",
    },
    "badge-info": {
      background: "#eff6ff",
      color: "#2563eb",
    },
    "image-container": {
      margin: "24px 0",
      border: "1px solid #e5e5e5",
      borderRadius: "10px",
      overflow: "hidden",
      background: "#fafafa",
    },
    "image-caption": {
      padding: "12px 16px",
      fontSize: "13px",
      color: "#737373",
      textAlign: "center",
      borderTop: "1px solid #e5e5e5",
      background: "#fff",
    },
    "keyboard-shortcut": {
      display: "inline-flex",
      gap: "4px",
    },
    key: {
      padding: "4px 8px",
      background: "#f5f5f5",
      border: "1px solid #d4d4d4",
      borderRadius: "6px",
      fontSize: "12px",
      fontFamily: "SF Mono, Monaco, monospace",
      color: "#404040",
      boxShadow: "0 1px 2px rgba(0, 0, 0, 0.05)",
    },
    "example-wrapper": {
      margin: "20px 0",
      border: "1px solid #e5e5e5",
      borderRadius: "10px",
      overflow: "hidden",
    },
    "example-label": {
      padding: "8px 16px",
      background: "#f5f5f5",
      borderBottom: "1px solid #e5e5e5",
      fontSize: "11px",
      fontWeight: 600,
      color: "#737373",
      textTransform: "uppercase",
      letterSpacing: "0.5px",
    },
    "example-content": {
      padding: "20px",
      background: "#fff",
      display: "block",
    },
    "badge-row": {
      display: "flex",
      gap: "8px",
      flexWrap: "wrap",
    },
    "keyboard-row": {
      display: "flex",
      gap: "24px",
      flexWrap: "wrap",
    },
    "keyboard-label": {
      color: "#737373",
      fontSize: "13px",
      marginRight: "8px",
    },
    "color-grid": {
      display: "grid",
      gridTemplateColumns: "repeat(4, 1fr)",
      gap: "16px",
      margin: "20px 0",
    },
    "color-swatch": {
      border: "1px solid #e5e5e5",
      borderRadius: "10px",
      overflow: "hidden",
    },
    "color-preview": {
      height: "64px",
    },
    "color-info": {
      padding: "12px",
      background: "#fff",
    },
    "color-name": {
      fontSize: "13px",
      fontWeight: 600,
      color: "#0a0a0a",
      marginBottom: "4px",
    },
    "color-value": {
      fontSize: "12px",
      fontFamily: "SF Mono, Monaco, monospace",
      color: "#737373",
    },
    "footer-nav": {
      display: "flex",
      justifyContent: "space-between",
      marginTop: "60px",
      paddingTop: "24px",
      borderTop: "1px solid #e5e5e5",
    },
    "footer-link": {
      display: "flex",
      flexDirection: "column",
      gap: "4px",
      textDecoration: "none",
      padding: "12px 16px",
      border: "1px solid #e5e5e5",
      borderRadius: "8px",
      minWidth: "180px",
    },
    "footer-label": {
      fontSize: "11px",
      color: "#737373",
      textTransform: "uppercase",
      letterSpacing: "0.5px",
    },
    "footer-title": {
      fontSize: "14px",
      fontWeight: 500,
      color: "#0a0a0a",
    },
  },
];
