import type { ComponentStylesheets } from "../../natural-html/design-system.ts";

export const sidebarStyles: ComponentStylesheets = [
  {
    "sidebar-header": {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      paddingBottom: "16px",
      borderBottom: "1px solid #e5e5e5",
    },
    logo: {
      display: "flex",
      alignItems: "center",
      gap: "8px",
      fontWeight: 600,
      fontSize: "15px",
      color: "#0a0a0a",
      textDecoration: "none",
    },
    "logo-icon": {
      width: "24px",
      height: "24px",
      background: "linear-gradient(135deg, #f97316 0%, #ea580c 100%)",
      borderRadius: "6px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      color: "white",
      fontSize: "12px",
      fontWeight: "bold",
    },
    "theme-toggle": {
      width: "32px",
      height: "32px",
      border: "1px solid #e5e5e5",
      borderRadius: "6px",
      background: "transparent",
      cursor: "pointer",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      color: "#737373",
      transition: "all 0.15s ease",
    },
    "search-bar": {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      padding: "8px 12px",
      background: "#f5f5f5",
      border: "1px solid #e5e5e5",
      borderRadius: "8px",
      cursor: "pointer",
      transition: "all 0.15s ease",
    },
    "search-left": {
      display: "flex",
      alignItems: "center",
      gap: "8px",
      color: "#737373",
    },
    "search-icon": {
      width: "16px",
      height: "16px",
    },
    "search-placeholder": {
      fontSize: "13px",
    },
    "search-shortcut": {
      display: "flex",
      gap: "4px",
    },
    kbd: {
      padding: "2px 6px",
      background: "#ffffff",
      border: "1px solid #e5e5e5",
      borderRadius: "4px",
      fontSize: "11px",
      fontFamily: "inherit",
      color: "#737373",
    },
    "subject-selector-wrapper": {
      position: "relative",
      marginBottom: "0",
    },
    "subject-selector": {
      display: "flex",
      alignItems: "center",
      gap: "10px",
      padding: "8px 12px",
      background: "#ffffff",
      border: "1px solid #e5e5e5",
      borderRadius: "8px",
      cursor: "pointer",
      transition: "all 0.15s ease",
      width: "100%",
      textAlign: "left",
    },
    "subject-selector-icon": {
      width: "24px",
      height: "24px",
      background: "linear-gradient(135deg, #f59e0b, #d97706)",
      borderRadius: "6px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      flexShrink: 0,
    },
    "subject-selector-name": {
      flex: "1",
      fontSize: "14px",
      fontWeight: 500,
      color: "#0a0a0a",
    },
    "selector-chevrons": {
      width: "16px",
      height: "16px",
      color: "#737373",
      flexShrink: 0,
    },
    "subject-popup": {
      position: "absolute",
      top: "calc(100% + 8px)",
      left: 0,
      right: 0,
      background: "#ffffff",
      border: "1px solid #e5e5e5",
      borderRadius: "12px",
      boxShadow: "0 10px 40px rgba(0, 0, 0, 0.1)",
      zIndex: 100,
      overflow: "hidden",
      opacity: 0,
      visibility: "hidden",
      transform: "translateY(-8px)",
      transition: "all 0.2s ease",
    },
    "subject-option": {
      display: "flex",
      alignItems: "flex-start",
      gap: "12px",
      padding: "12px 16px",
      cursor: "pointer",
      transition: "background 0.15s ease",
    },
    "option-icon": {
      width: "28px",
      height: "28px",
      borderRadius: "6px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      flexShrink: 0,
      background: "#f3f4f6",
    },
    "option-info": {
      flex: "1",
    },
    "option-title": {
      fontSize: "14px",
      fontWeight: 500,
      color: "#0a0a0a",
    },
    "option-description": {
      fontSize: "12px",
      color: "#737373",
      marginTop: "2px",
    },
    "option-checkmark": {
      width: "16px",
      height: "16px",
      color: "#f97316",
      opacity: 0,
      marginTop: "4px",
    },
    "nav-section": {
      display: "flex",
      flexDirection: "column",
      gap: "4px",
    },
    "nav-category": {
      fontSize: "11px",
      fontWeight: 600,
      color: "#737373",
      textTransform: "uppercase",
      letterSpacing: "0.5px",
      padding: "8px 0 4px 0",
      marginTop: "8px",
    },
    "nav-link": {
      display: "flex",
      alignItems: "center",
      gap: "8px",
      padding: "8px 12px",
      borderRadius: "6px",
      textDecoration: "none",
      color: "#525252",
      fontSize: "13px",
      position: "relative",
      transition: "all 0.15s ease",
    },
    "nav-link-active": {
      background: "#fff7ed",
      color: "#ea580c",
      fontWeight: 500,
    },
    "nav-link-indicator": {
      position: "absolute",
      left: 0,
      width: "3px",
      height: "24px",
      background: "#f97316",
      borderRadius: "0 2px 2px 0",
      top: "50%",
      transform: "translateY(-50%)",
    },
    "nav-icon": {
      width: "16px",
      height: "16px",
      opacity: 0.7,
    },
    "nav-expandable": {
      display: "flex",
      flexDirection: "column",
    },
    "nav-toggle": {
      display: "flex",
      alignItems: "center",
      gap: "8px",
      padding: "8px 12px",
      borderRadius: "6px",
      textDecoration: "none",
      color: "#525252",
      fontSize: "13px",
      cursor: "pointer",
      background: "none",
      border: "none",
      width: "100%",
      textAlign: "left",
      fontFamily: "inherit",
      transition: "all 0.15s ease",
    },
    "nav-chevron": {
      width: "14px",
      height: "14px",
      marginLeft: "auto",
      opacity: 0.6,
      transition: "transform 0.2s ease",
    },
    "nav-children": {
      marginLeft: "20px",
      paddingLeft: "12px",
      borderLeft: "1px solid #e5e5e5",
      display: "flex",
      flexDirection: "column",
      gap: "2px",
      marginTop: "2px",
    },
    "nav-child-link": {
      display: "block",
      padding: "6px 12px",
      fontSize: "13px",
      color: "#525252",
      textDecoration: "none",
      borderRadius: "4px",
      transition: "all 0.15s ease",
    },
    "nav-child-link-active": {
      color: "#ea580c",
      background: "#fff7ed",
    },
  },
];
